Feature/password confirmation
YucenLyc/Releasify pull request #2
Opened 2021-11-13 21:24 UTC by YucenLyc

2021-11-13 21:37 UTC, digorithm commented on client/my-app/src/Pages/Register.js
> +      axios.post("http://localhost:3000/api/users/register", {
The _base_ url (`http://localhost:3000`) needs to be an environment variable.

Once this is deployed to a real environment the name (`localhost` part) might not be `localhost`, it might be an actual name `api.releasefy.com`, the port might be something different. Worse, these 2 parts of the URL (`$name:$port`) might change all the time. It would be cumbersome to change the *codebase* in order to make these changes, right?

A better approach is to read the base URL path from an environment variable, say `API_BASE_URL` where you have the flexibility to change its value, within the context of the machine that'll be running the code, without changing the codebase itself! 

_How_ you're gonna do this is very flexible, there are many right ways to do it. Just keep it simple. You could, above the `const register = () => {` line, add another `const`, like `const baseURL = process.env.API_BASE_URL` and at `axios.post()` you pass `baseURL +  "/api/users/register"`

More here: https://medium.com/the-node-js-collection/making-your-node-js-work-everywhere-with-environment-variables-2da8cdf6e786

2021-11-13 21:38 UTC, digorithm commented on client/my-app/src/Pages/UserInfo.js
> +    axios.get("http://localhost:3000/api/auth/login/userInfo" , {
Same here, `http://localhost:3000/api/auth/login/userInfo` would eventually be `baseURL + "/api/auth/login/userInfo"`

2021-11-13 21:39 UTC, digorithm commented on server/index.js
>  app.listen(3000, () => {
This port should also be coming from an environment variable and not a hardcoded value

2021-11-13 21:41 UTC, digorithm commented on server/routes/auth-routes.js
> +    console.log(userInfo.rows);
So right now anyone hitting the `login/userInfo` endpoint can list every user's information? Seems like that comment there is a `TODO`, right? If that's the case and it's future work, make it `// TODO: need to make sure only the logged in user gets the personal information on this page`

2021-11-13 21:43 UTC, digorithm requested changes
Looking good, just those comments I posted before about env vars and proper `TODO` documentation.

2021-11-13 21:47 UTC, YucenLyc commented on server/routes/auth-routes.js
> +    console.log(userInfo.rows);
Yes, that is a TODO to remind my future self. Right now, I'm only redirecting users who are logged in to "login/userInfo" route, but that's not enough. I need to send an error message to users who are not logged in and try to access this route. For now, users who do not have access just get stuck at the login page with no error message showing.

2021-11-14 02:51 UTC, YucenLyc commented on client/my-app/src/Pages/Register.js
> +      axios.post("http://localhost:3000/api/users/register", {
updated the base url to be an environment variable

2021-11-14 03:27 UTC, digorithm approved these changes

2021-11-14 03:28 UTC, merged