Debug/validating registration
YucenLyc/Releasify pull request #3
Opened 2022-05-23 21:04 UTC by YucenLyc

2022-06-10 01:13 UTC, christophercpang requested changes
Couple of comments - let me know if you have any questions!

2022-06-10 01:13 UTC, christophercpang commented on server/routes/auth-routes.js
> +    console.log("password:", password);
Remove console logs if not required

2022-06-10 01:13 UTC, christophercpang commented on server/routes/users-routes.js
> +router.post('/testing', (req, res) => {
Do we still need this testing route?

2022-06-10 01:13 UTC, christophercpang commented on server/routes/users-routes.js
> +    console.log(newUser)
Remove console logs

2022-06-10 03:22 UTC, YucenLyc commented on client/frontend-releasify/src/Pages/Register.js
> +        password: password,
good to know!! ty!

2022-06-10 03:42 UTC, YucenLyc commented on server/routes/users-routes.js
> +router.post('/testing', (req, res) => {
Actually, no, will remove it!

2022-06-12 20:37 UTC, christophercpang commented on client/frontend-releasify/src/Pages/Login.js
> +export default function Login() {
I think we should keep our code consistent in terms of how we define functions, so let's change this to

```
const Login = () => {
...
}

export default Login
```

2022-06-12 21:25 UTC, christophercpang approved these changes
Looks good!

2022-06-12 21:29 UTC, merged

2022-06-12 21:30 UTC, YucenLyc commented
fix registration FE error; clean up code;